# Generated by Django 4.2.1 on 2023-06-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Author', models.CharField(max_length=30)),
                ('PDF', models.FileField(upload_to='book/pdf')),
                ('Cover', models.ImageField(blank=True, null=True, upload_to='book/cover')),
            ],
        ),
    ]
