# Generated by Django 4.2.1 on 2023-05-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
